sudo: required
dist: trusty
language: c++

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
  - cd ser-player
  - export QT_SELECT=5
  - qmake CONFIG+=release
  - make
