language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh
  
script:
  # Build SER-Player with version checking disabled (aimed at Linux repositories)
  - qmake DEFINES+=DISABLE_NEW_VERSION_CHECK CONFIG+=release
  - make
  - ls -l bin/
  - ldd bin/ser-player
  
  # Cleanup between builds
  #- make clean
  
  # Build SER-Player with version checking enabled
  #- qmake CONFIG+=release
  #- make
  #- ls -l bin/
  #- ldd bin/ser-player