language: cpp
compiler: gcc
sudo: require
dist: trusty

git:
  depth: false

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh
  
script:
  # Build SER-Player with version checking disabled (aimed at Linux repositories)
  - qmake DEFINES+=DISABLE_NEW_VERSION_CHECK CONFIG+=release
  - make
  - ls -l bin/
  - ldd bin/ser-player
  
  # Cleanup between builds
  - make clean
  
  # Build SER-Player with version checking enabled ready to make an AppImage
  - source appimage/make_appimage.sh
  - ls -l SER_Player-*.AppImage

after_success:
  - ls -l SER_Player-*.AppImage
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh SER_Player*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
