language: cpp
compiler: gcc
sudo: require
dist: trusty

git:
  depth: false

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510base
  - source /opt/qt*/bin/qt*-env.sh
  
script:
  # Build SER-Player with default options as would be build by a user to install on her own system
  - qmake CONFIG+=release
  - make
  - ls -l bin/
  - ldd bin/ser-player
  
  # Cleanup between builds
  - make clean
  - rm -rf bin build
  
  # Build SER-Player with version checking disabled (aimed at Linux repositories)
  - qmake CONFIG+=release BUILD_FOR_REPOSITORY=
  - make
  - ls -l bin/
  - ldd bin/ser-player
  
  # Cleanup between builds
  - make clean
  - rm -rf bin build
  
  # Build AppImage version of SER Player.
  - source appimage/make_appimage.sh
  - ls -l SER_Player-*.AppImage

after_success:
  - ls -l SER_Player-*.AppImage
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh SER_Player*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
